schema: 1

group: Basic Parts

  item: Aluminium Plate
    recipe:
        input: Aluminium Ingot, Engineer's Hammer
        pattern: 01. ... ...
        quantity: 1

  item: Aluminium Rod
    recipe:
        input: Aluminium Ingot
        pattern: 0.. 0.. ...
        quantity: 4

# item: Aluminium Sheet Metal Block
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

  item: Constantan Plate
    recipe:
        input: Constantan Ingot, Engineer's Hammer
        pattern: 01. ... ...
        quantity: 1

# item: Copper Wire Coil
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Electrum Wire Coil
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Focused Nozzle
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Graphite Electrode
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Hemp Rope Coil
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Hempcrete
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Industrial Hemp
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Iron Mechanical Component
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

  item: Iron Plate
    recipe:
        input: Iron Ingot, Engineer's Hammer
        pattern: 01. ... ...
        quantity: 1

  item: Iron Rod
    recipe:
        input: Iron Ingot
        pattern: 0.. 0.. ...
        quantity: 4

# item: Insulating Glass
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Lantern
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

  item: Lead Plate
    recipe:
        input: Lead Ingot, Engineer's Hammer
        pattern: 01. ... ...
        quantity: 1

# item: Powered Lantern
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Precision Scope
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Pressurized Air Tank
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Redstone Breaker
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Revolver Barrel
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Revolver Drum
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1sl
#        tools: Crafting Table

# item: Revolver Hammer
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Revolver Speedloader
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Slag
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Steel Cable Coil
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

  item: Steel Plate
    recipe:
        input: Steel Ingot, Engineer's Hammer
        pattern: 01. ... ...
        quantity: 1

  item: Steel Rod
    recipe:
        input: Steel Ingot
        pattern: 0.. 0.. ...
        quantity: 4

# item: Tough Fabric
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

  item: Treated Stick
    recipe:
        input: Treated Wood Planks
        pattern: 0.. 0.. ...
        quantity: 4
        tools: Crafting Table

 item: Treated Wood Doubleslab
    recipe:
        input:
        pattern: ... ... ...
        quantity: 1
        tools: Crafting Table

# item: Treated Wood Fence
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

 item: Treated Wood Planks
    recipe:
        input: Bottle of Creosote Oil, Oak Wood Planks
        pattern: 111 101 111
        quantity: 8
        tools: Crafting Table

# item: Wooden Grip
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Wooden Post
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Wooden Storage Crate
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Wooden Wall Mount
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

group: Basic Tools

  item: Engineer's Blueprint
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

  item: Engineer's Hammer
    recipe:
      input: Iron Ingot, Stick, String
        pattern: .02 .10 1..
        quantity: 1
        tools: Crafting Table

  item: Engineer's Manual
    recipe:
      input: Book, Lever
        pattern: 01. ... ...
        quantity: 1

# item: Engineer's Skyhook
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Engineer's Toolbox
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

  item: Engineer's Voltmeter
    recipe:
      input: Compass, Copper Ingot, Treated Stick
        pattern: .0. 212 .1.
        quantity: 1
        tools: Crafting Table

  item: Engineer's Wire Cutters
    recipe:
      input: Iron Ingot, Treated Stick
        pattern: 10. .1. ...
        quantity: 1

# item: Engineer's Workbench
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

group: Resources

  item: Copper Ore; gatherable: yes

  item: Bauxite Ore; gatherable: yes

  item: Lead Ore; gatherable: yes

  item: Nickel Ore; gatherable: yes

  item: Silver Ore; gatherable: yes

  item: Block of Aluminium
    recipe:
        input: Aluminium Ingot
        pattern: 000 000 000
        quantity: 1
        tools: Crafting Table

  item: Block of Coal Coke
    recipe:
        input: Coal Coke
        pattern: 000 000 000
        quantity: 1
        tools: Crafting Table

  item: Block of Constantan
    recipe:
        input: Constantan Ingot
        pattern: 000 000 000
        quantity: 1
        tools: Crafting Table

  item: Block of Copper
    recipe:
        input: Copper Ingot
        pattern: 000 000 000
        quantity: 1
        tools: Crafting Table

  item: Block of Electrum
    recipe:
        input: Electrum Ingot
        pattern: 000 000 000
        quantity: 1
        tools: Crafting Table

  item: Block of Lead
    recipe:
        input: Lead Ingot
        pattern: 000 000 000
        quantity: 1
        tools: Crafting Table

  item: Block of Nickel
    recipe:
        input: Nickel Ingot
        pattern: 000 000 000
        quantity: 1
        tools: Crafting Table

  item: Block of Silver
    recipe:
        input: Silver Ingot
        pattern: 000 000 000
        quantity: 1
        tools: Crafting Table

  item: Block of Steel
    recipe:
        input: Steel Ingot
        pattern: 000 000 000
        quantity: 1
        tools: Crafting Table

 item: Aluminium Grit
    recipe:
        input: Bauxite Ore
        pattern: 0.. ... ...
        quantity: 2
        tools: Crusher

  item: Aluminium Ingot
    recipe:
        input: Aluminium Grit, Fuel
        pattern: .0. ... .1.
        quantity: 1
        tools: Furnace

  item: Aluminium Nugget
    recipe:
        input: Aluminium Ingot
        pattern: 0.. ... ...
        quantity: 9

  item: Constantan Grit
    recipe:
        input: Copper Grit, Nickel Grit
        pattern: 01. ... ...
        quantity: 2

  item: Constantan Ingot
    recipe:
        input: Constantan Grit, Fuel
        pattern: .0. ... .1.
        quantity: 1
        tools: Furnace

  item: Constantan Nugget
    recipe:
        input: Constantan Ingot
        pattern: 0.. ... ...
        quantity: 9

  item: Copper Grit
    recipe:
        input: Copper Ore
        pattern: 0.. ... ...
        quantity: 2
        tools: Crusher

  item: Copper Ingot
    recipe:
        input: Copper Grit
        pattern: ... ... ...
        quantity: 1
        tools: Furnace

  item: Copper Nugget
    recipe:
        input: Copper Ingot
        pattern: 0.. ... ...
        quantity: 9

  item: Electrum Grit
    recipe:
        input: Gold Grit, Silver Grit
        pattern: 01. ... ...
        quantity: 2

  item: Electrum Ingot
    recipe:
        input: Electrum Grit, Fuel
        pattern: .0. ... .1.
        quantity: 1
        tools: Furnace

  item: Electrum Nugget
    recipe:
        input: Electrum Ingot
        pattern: 0.. ... ...
        quantity: 9

  item: Gold Grit
    recipe:
        input: Gold Ore
        pattern: 0.. ... ...
        quantity: 2
        tools: Crusher

  item: HOP Graphite Dust
    recipe:
        input: Coke Dust
        pattern: .0. ... ...
        quantity: 1
        tools: Industrial Squeezer

  item: HOP Graphite Ingot
    recipe:
        input: HOP Graphite Dust, Fuel
        pattern: .0. ... .1.
        quantity: 1
        tools: Furnace

  item: Industrial Hemp Fiber
    recipe:
        input: Industrial Hemp Seeds, Soil
        pattern: .0. .1. ...
        quantity: 1
        
  item: Industrial Hemp Seeds; gatherable: yes

  item: Iron Grit
    recipe:
        input: Iron Ore
        pattern: 0.. ... ...
        quantity: 2
        tools: Crusher

  item: Iron Nugget
    recipe:
        input: Iron Ingot
        pattern: 0.. ... ...
        quantity: 9

  item: Lead Grit
    recipe:
        input: Lead Ore
        pattern: 0.. ... ...
        quantity: 2
        tools: Crusher

  item: Lead Ingot
    recipe:
        input: Lead Grit, Fuel
        pattern: .0. ... .1.
        quantity: 1
        tools: Furnace

  item: Lead Nugget
    recipe:
        input: Lead Ingot
        pattern: 0.. ... ...
        quantity: 9

  item: Nickel Grit
    recipe:
        input: Nickel Ore
        pattern: 0.. ... ...
        quantity: 2
        tools: Crusher

  item: Nickel Ingot
    recipe:
        input: Nickel Grit, Fuel
        pattern: .0. ... .1.
        quantity: 1
        tools: Furnace

  item: Nickel Nugget
    recipe:
        input: Nickel Ingot
        pattern: 0.. ... ...
        quantity: 9

  item: Quartz Dust
    recipe:
        input: Nether Quartz
        pattern: .0. ... ...
        quantity: 1
        tools: Crusher

  item: Silver Grit
    recipe:
        input: Silver Ore
        pattern: .0. ... ...
        quantity: 2
        tools: Crusher

  item: Silver Ingot
    recipe:
        input: Silver Grit, Fuel
        pattern: .0. ... .1.
        quantity: 1
        tools: Furnace

  item: Silver Nugget
    recipe:
        input: Silver Ingot
        pattern: .0. ... ...
        quantity: 9

  item: Steel Ingot
    recipe:
        input: Iron Ingot, Coal Coke
        pattern: .0. ... .1.
        quantity: 1
        tools: Blast Furnace

  item: Steel Nugget
    recipe:
        input: Steel Ingot
        pattern: .0. ... ...
        quantity: 9

group: Bullets

  item: Empty Casing
    recipe:
      input: Copper Ingot
      pattern: 0.0 0.0 .0.
      quantity: 3
      tools: Crafting Table

  item: Empty Shell
    recipe:
      input: Rose Red, Paper, Copper Ingot
      pattern: 101 101 .2.
      quantity: 3
      tools: Crafting Table

# item: Casull Cartridge
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Armor-Piercing Cartridge
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Buckshot Cartridge
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Dragon's Breath Cartridge
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: High-Explosive Cartridge
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Homing Cartridge
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Phial Cartridge
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Silver Cartridge
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Wolfpack Cartridge
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

group: Drill

# item: Iron Drill Head
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Mining Drill
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Steel Drill Head
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

group: Ranged Weapons

# item: Chemical Thrower
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Revolver
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Railgun
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

group: Tool Upgrades

# item: Additional Augers
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Additional Capacitors
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Advanced Lubrication System
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Amplifier Electron Tubes
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Bayonet
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Extended Magazine
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

group: Building Blocks

# item: Aluminium Fence
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Aluminium Scaffolding
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

  item: Aluminium Slab
    recipe:
        input: Block of Aluminium
        pattern: 000 ... ...
        quantity: 6
        tools: Crafting Table

# item: Aluminium Structural Arm
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Blast Brick
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Concrete Stairs
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Concrete Tile Stairs
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Concrete Tile
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Concrete
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

  item: Constantan Slab
    recipe:
        input: Block of Constantan
        pattern: 000 ... ...
        quantity: 6
        tools: Crafting Table

  item: Copper Slab
    recipe:
        input: Block of Copper
        pattern: 000 ... ...
        quantity: 6
        tools: Crafting Table

  item: Electrum Slab
    recipe:
        input: Block of Electrum
        pattern: 000 ... ...
        quantity: 6
        tools: Crafting Table

# item: Fermenter
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Floodlight
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Fluid Pipe
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Fluid Pump
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Generator Block
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Heavy Engineering Block
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Industrial Squeezer
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Item Router
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Jerrycan
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Kinetic Dynamo
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Large Tank
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Lead Sheet Metal Block
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

  item: Lead Slab
   recipe:
        input: Block of Lead
        pattern: 000 ... ...
        quantity: 6
        tools: Crafting Table

# item: Light Engineering Block
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Lightning Rod Base
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Metal Barrel
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

  item: Nickel Slab
    recipe:
        input: Block of Nickel
        pattern: 000 ... ...
        quantity: 6
        tools: Crafting Table

# item: Radiator Block
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Reinforced Blast Brick
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Sheet Metal Block
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

  item: Silver Slab
    recipe:
        input: Block of Silver
        pattern: 000 ... ...
        quantity: 6
        tools: Crafting Table

  item: Steel Fence
    recipe:
        input: Steel Rod
        pattern: 000 000 ...
        quantity: 2
        tools: Crafting Table

# item: Steel Mechanical Component
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

  item: Steel Scaffolding
    recipe:
        input: Steel Ingot, Steel Fence
        pattern: 000 .1. 1.1
        quantity: 6
        tools: Crafting Table

# item: Steel Sheet Metal Block
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

  item: Steel Slab
    recipe:
        input: Block of Steel
        pattern: 000 ... ...
        quantity: 6
       tools: Crafting Table

# item: Steel Wall Mount
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Structural Arm
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Structural Cable Connector
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Treated Wood Scaffolding
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

  item: Treated Wood Slab
    recipe:
        input: Treated Wood Planks
        pattern: 000 ... ...
        quantity: 6
        tools: Crafting Table

# item: Treated Wood Stairs
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Wooden Barrel
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table


group: Structures

# item: Balloon
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Blast Furnace Preheater
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Construction Mark
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

  item: Conveyor Belt
    recipe:
        input: Leather, Iron Ingot, Redstone Dust
        pattern: 000 121 ...
        quantity: 8
        tools: Crafting Table

# item: Core Sample Drill
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Dropping Conveyor Belt
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: External Heater
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

group: Liquids

# item: Bottle of Biodiesel
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Bottle of Creosote Oil
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Bottle of Ethanol
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Bottle of Plant Oil
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Bucket of Biodiesel
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Bucket of Creosote Oil
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Bucket of Ethanol
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Bucket of Plant Oil
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

group: Fuels

  item: Coal Coke
    recipe:
        input: Coal
        pattern: .0. ... ...
        quantity: 1
        tools: Coke Oven

# item: Coke Brick
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

  item: Coke Dust
    recipe:
        input: Coal Coke
        pattern: .0. ... ...
        quantity: 1
        tools: Crusher

group: Metal Press

# item: Metal Press Mold_ Gear
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Metal Press Mold_ Plate
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Metal Press Mold_ Rod
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

group: Power Generation

# item: Improved Windmill Blade
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Improved Windmill
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Thermoelectric Generator
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Water Wheel
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Waterwheel Segment
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Windmill Blade
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Windmill
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

group: Power Transmission

# item: Breaker Switch
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Charging Station
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Current Transformer
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: High-Voltage Wire Coil
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: HV Capacitor
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: HV Transformer
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: HV Wire Coil
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: HV Wire Connector
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: HV Wire Relay
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: LV Capacitor
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: LV Wire Coil
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: LV Wire Connector
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: MV Capacitor
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: MV Wire Coil
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: MV Wire Connector
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Transformer
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

group: Food

# item: Berry Medley
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

group: Shaders

# item: Common Shader Grabbag
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Cosmic Shader Grabbag
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Epic Shader Grabbag
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Rare Shader Grabbag
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Relic Shader Grabbag
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Uncommon Shader Grabbag
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Aero
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Angel's Thesis
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Argo
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Chloris
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Cosmic
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Crescent Rose
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Dragon's Breath
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Falconmoon
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Felix
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Fox
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Glacis
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Harrowed
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Hollow
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Locus
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Magnum
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Mass Fusion
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Matrix
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Miló
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Phoenix
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Qrow
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Radiant
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Regal
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Rosequartz
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Sharkface
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Solum
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Spectral
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Sponsor
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ StormFlower
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Sunstrike
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Taken
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Trident
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Vanguard
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Vault-Tec
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Shader_ Warbird
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table
