schema: 1

group: Basic Parts

# item: Aluminium Plate
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Aluminium Rod
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Aluminium Sheet Metal Block
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Constantan Plate
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Iron Plate
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Iron Rod
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Lead Plate
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Steel Plate
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Steel Rod
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Treated Stick
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Treated Wood Doubleslab
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Treated Wood Fence
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Treated Wood Planks
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Wooden Grip
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Wooden Post
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Wooden Storage Crate
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Wooden Wall Mount
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table
group: Basic Tools

  item: Engineer's Hammer
    recipe:
      input: Iron Ingot, Stick, String
        pattern: .02 .10 1..
        quantity: 1
        tools: Crafting Table

  item: Engineer's Manual
    recipe:
      input: Book, Lever
        pattern: 01. ... ...
        quantity: 1

# item: Engineer's Skyhook
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Engineer's Toolbox
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

  item: Engineer's Voltmeter
    recipe:
      input: Compass, Copper Ingot, Treated Stick
        pattern: .0. 212 .1.
        quantity: 1
        tools: Crafting Table

  item: Engineer's Wire Cutters
    recipe:
      input: Iron Ingot, Treated Stick
        pattern: 10. .1. ...
        quantity: 1

# item: Engineer's Workbench
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

group: Metals

  item: Copper Ore; gatherable: yes

  item: Bauxite Ore; gatherable: yes

  item: Lead Ore; gatherable: yes

  item: Nickel Ore; gatherable: yes

  item: Silver Ore; gatherable: yes

# item: Block of Aluminium
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Block of Coal Coke
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Block of Constantan
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Block of Copper
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Block of Electrum
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Block of Lead
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Block of Nickel
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Block of Silver
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Block of Steel
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Aluminium Grit
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Aluminium Ingot
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Aluminium Nugget
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Constantan Grit
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Constantan Ingot
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Constantan Nugget
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Copper Grit
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Copper Ingot
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Copper Nugget
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Electrum Grit
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Electrum Ingot
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Electrum Nugget
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Gold Grit
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Iron Grit
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Iron Nugget
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Lead Grit
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Lead Ingot
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Lead Nugget
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Nickel Grit
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Nickel Ingot
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Nickel Nugget
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Silver Grit
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Silver Ingot
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Silver Nugget
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Steel Ingot
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Steel Nugget
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

group: Bullets

  item: Empty Casing
    recipe:
      input: Copper Ingot
      pattern: 0.0 0.0 .0.
      quantity: 3
      tools: Crafting Table

  item: Empty Shell
    recipe:
      input: Rose Red, Paper, Copper Ingot
      pattern: 101 101 .2.
      quantity: 3
      tools: Crafting Table

# item: Casull Cartridge
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Armor-Piercing Cartridge
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Buckshot Cartridge
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Dragon's Breath Cartridge
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: High-Explosive Cartridge
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Homing Cartridge
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Phial Cartridge
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Silver Cartridge
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Wolfpack Cartridge
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

group: Blueprints

  item: Engineer's Blueprint
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Engineer's Blueprint_2
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Engineer's Blueprint_3
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

group: Drill

group: Ranged Weapons

# item: Chemical Thrower
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

group: Tool Upgrades

# item: Additional Augers
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Additional Capacitors
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Advanced Lubrication System
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Amplifier Electron Tubes
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

group: Building Blocks

# item: Aluminium Fence
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Aluminium Scaffolding
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Aluminium Scaffolding_2
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Aluminium Slab
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Aluminium Structural Arm
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Blast Brick
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Concrete Stairs
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Concrete Tile Stairs
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Concrete Tile
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Concrete
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Constantan Slab
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Copper Slab
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Electrum Slab
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Heavy Engineering Block
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Lead Sheet Metal Block
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Lead Slab
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Light Engineering Block
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Treated Wood Scaffolding
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Treated Wood Slab
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Treated Wood Stairs
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Wooden Barrel
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

group: Structures

# item: Balloon
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Blast Furnace Preheater
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Conveyor Belt
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Core Sample Drill
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

group: Liquids

# item: Bottle of Biodiesel
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Bottle of Creosote Oil
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Bottle of Ethanol
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Bottle of Plant Oil
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Bucket of Biodiesel
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Bucket of Creosote Oil
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Bucket of Ethanol
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Bucket of Plant Oil
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

group: Fuels

# item: Coal Coke
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Coke Brick
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Coke Dust
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

group: Metal Press

# item: Metal Press Mold_ Gear
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Metal Press Mold_ Plate
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Metal Press Mold_ Rod
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

group: Power Generation

# item: Improved Windmill Blade
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Improved Windmill
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Thermoelectric Generator
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Water Wheel
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Waterwheel Segment
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Windmill Blade
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table

# item: Windmill
#    recipe:
#        input:
#        pattern: ... ... ...
#        quantity: 1
#        tools: Crafting Table
