schema: 1

name:             Immersive Engineering
author:           BluSunrize
description:      A retro-futuristic tech mod! Wires, transformers, capacitors!
homePageUrl:      http://mods.curse.com/mc-mods/minecraft/231951-immersive-engineering
documentationUrl: http://mods.curse.com/mc-mods/minecraft/231951-immersive-engineering
downloadUrl:      http://mods.curse.com/mc-mods/minecraft/231951-immersive-engineering/download

version: 0.7.1.2
